### PR TITLE
Included java for firestore emulator

### PR DESCRIPTION
**Pull request by mhbrooks**

### CODE REVIEW

**Comment by ashsmith** [comment]
Does this add much to the new image size? I'd be concerned about having monster docker images that circleci has to pull down before a job even starts

**Comment by mhbrooks** [comment]
Takes it from 891->971 so a decent 80MB but % not a big deal, we can consider splitting out into multiple to bring that down if it starts becoming an issue but circle fetching tends to be pretty quick

**Comment by mhbrooks** [comment]
Happy to take the popular opinion here though

**Comment by mhbrooks** [comment]
👍 Lets go with this for now, i'll keep an eye on fetch metrics.

**Pull request merged**
